name: Build Tracy Java Bindings

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]
      fail-fast: false

    steps:
    # Checkout des Repositorys
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup für JDK
    - name: Setup Java 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build Tracy
      run: |
        ./gradlew jar
